edenlabllc/ops.api

- lib/ops/declaration/declarations_status_hstr.ex
- priv/repo/migrations/20170718084250_add_declarations_status_hstr.exs
- test/unit/web/controllers/declaration_test.exs
https://github.com/Nebo15/ehealth.api/issues/646
> add declarations_stats_hstr table and trigger to fill it

- lib/ops/declaration/declaration.ex
- lib/ops/declaration/declarations.ex
- priv/repo/migrations/20170719140502_add_declaration_request_id_to_decl.exs
- test/unit/declaration_report_test.exs
- test/unit/declaration_test.exs
- test/unit/web/controllers/declaration_test.exs
Fixes https://github.com/Nebo15/ehealth.api/issues/621
> Add declaration_request_id to declarations

- lib/ops/declaration/declarations.ex
- test/unit/declaration_report_test.exs
- test/unit/declaration_test.exs
- test/unit/web/controllers/declaration_test.exs
https://github.com/edenlabllc/ehealth.api/issues/853
> Add ID to declarations that need to be passed from other services

- lib/ops/declaration/declarations.ex
https://github.com/edenlabllc/ehealth.api/issues/949
> allow only one active declaration for person

- lib/ops/declaration/declarations.ex
https://github.com/edenlabllc/ehealth.api/issues/949
> fix declarations termination logic

- lib/ops/medication_dispense/medication_dispense_status_hstr.ex
- lib/ops/medication_dispense/medication_dispenses.ex
- priv/repo/migrations/20170921085753_create_medication_dispense_history.exs
- test/integration/medication_dispenses_test.exs
- test/unit/web/controllers/medication_dispense_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1020
> remove is_active filter from list

- lib/ops/medication_dispense/medication_dispenses.ex
- lib/ops/medication_dispense/schema.ex
- lib/ops/medication_request/medication_requests.ex
- lib/ops/medication_request/schema.ex
- lib/ops/medication_request/search.ex
- lib/ops/web/controllers/medication_dispense_controller.ex
- lib/ops/web/controllers/medication_request_controller.ex
- lib/ops/web/router.ex
- lib/ops/web/views/medication_dispense_view.ex
- lib/ops/web/views/medication_request_view.ex
- priv/repo/migrations/20170913133450_create_medication_request.exs
- test/support/factory.ex
- test/unit/web/controllers/medication_dispense_controller_test.exs
- test/unit/web/controllers/medication_request_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/976
> create medication requests list endpoint

- lib/ops/medication_request/medication_request_status_hstr.ex
- priv/repo/migrations/20171006082140_create_medication_requests_status_hstr.exs
https://github.com/edenlabllc/ehealth.api/issues/1203
> add medication requests status history table

- lib/ops/ecto/uuids_list.ex
- lib/ops/medication_request/doctor_search.ex
- lib/ops/medication_request/medication_requests.ex
- lib/ops/medication_request/search.ex
- lib/ops/web/controllers/medication_request_controller.ex
- lib/ops/web/router.ex
- test/unit/web/controllers/medication_dispense_controller_test.exs
- test/unit/web/controllers/medication_request_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/976
> create medication requests doctors list endpoint

- lib/ops/medication_request/medication_requests.ex
- lib/ops/medication_request/person_search.ex
- lib/ops/web/controllers/medication_request_controller.ex
- lib/ops/web/router.ex
- lib/ops/web/views/medication_request_view.ex
- test/unit/web/controllers/medication_request_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/974
> create endpoint to search medication request ids for qualify

- lib/ops/medication_request/medication_requests.ex
- lib/ops/medication_request/search.ex
- test/unit/web/controllers/medication_request_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1174
> improve medication request filters

- lib/ops/medication_dispense/search.ex
- test/unit/web/controllers/medication_dispense_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1045
> add dispensed_at filter to dispenses list

- config/config.exs
- lib/ops/scheduler.ex
https://github.com/edenlabllc/ehealth.api/issues/978
> fix medication_request autotermination

- lib/ops/declaration/declarations.ex
https://github.com/edenlabllc/ehealth.api/issues/1370
> add audit log to all declaration processes

- lib/ops/medication_dispense/medication_dispenses.ex
- lib/ops/medication_dispense/search.ex
- test/unit/web/controllers/medication_dispense_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1419
> add date filters to medication dispenses list

- priv/repo/migrations/20171108115744_add_unique_indexes.exs
- test/support/factory.ex
- test/unit/declaration_test.exs
- test/unit/web/controllers/declaration_controller_test.exs
- test/unit/web/controllers/medication_request_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1089
> [patch] add unique indexes

- .env
- config/config.exs
- config/dev.exs
- config/prod.exs
- config/test.exs
- lib/ops/application.ex
- lib/ops/declaration/declarations.ex
- lib/ops/event_manager/event.ex
- lib/ops/event_manager/event_manager.ex
- lib/ops/event_manager_repo.ex
- lib/ops/medication_dispense/details.ex
- lib/ops/medication_dispense/medication_dispense.ex
- lib/ops/medication_dispense/medication_dispenses.ex
- lib/ops/medication_dispense/schema.ex
- lib/ops/medication_request/medication_request.ex
- lib/ops/medication_request/medication_requests.ex
- lib/ops/scheduler.ex
- mix.exs
- priv/event_manager_repo/migrations/20171127145251_create_audit_log.exs
- priv/event_manager_repo/migrations/20171127154946_create_events.exs
- test/integration/medication_dispenses_test.exs
- test/integration/medication_requests_test.exs
- test/support/conn_case.ex
- test/support/data_case.ex
- test/support/factory.ex
- test/test_helper.exs
- test/unit/web/controllers/declaration_controller_test.exs
- test/unit/web/controllers/medication_dispense_controller_test.exs
- test/unit/web/controllers/medication_request_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1525
> Event manager#1525

- lib/ops/event_manager/event_manager.ex
- test/integration/medication_dispenses_test.exs
- test/integration/medication_requests_test.exs
- test/unit/web/controllers/declaration_controller_test.exs
- test/unit/web/controllers/medication_request_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1595
> [minor] fix events properties structure

- lib/ops/declaration/declaration.ex
- lib/ops/declaration/declarations.ex
- lib/ops/web/controllers/declaration_controller.ex
- lib/ops/web/controllers/fallback_controller.ex
- lib/ops/web/router.ex
- lib/ops/web/views/declaration_view.ex
- priv/repo/migrations/20180228104523_add_overlimit.exs
- test/unit/web/controllers/declaration_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1838
> [patch] add count employees declarations endpoint

- lib/ops/web/controllers/declaration_controller.ex
- test/unit/web/controllers/declaration_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1838
> [patch] count declarations by comma separated employee_ids

- lib/ops/web/controllers/declaration_controller.ex
- lib/ops/web/router.ex
- test/unit/web/controllers/declaration_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1838
> [patch] use post for getting party declarations count

- lib/ops/declaration/declaration.ex
- lib/ops/declaration/declarations.ex
- test/unit/web/controllers/declaration_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1838
> [patch] save declaration overlimit field

- lib/ops/declaration/declarations.ex
- lib/ops/web/controllers/declaration_controller.ex
- lib/ops/web/router.ex
- test/unit/web/controllers/declaration_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/t
> [patch] add declaration terminate endpoint

- lib/ops/declaration/declaration.ex
- lib/ops/declaration/declarations.ex
- priv/repo/migrations/20180320100119_add_declaration_number.exs
- priv/repo/migrations/20180320104249_set_declaration_number.exs
- test/support/factory.ex
- test/unit/declaration_test.exs
- test/unit/web/controllers/declaration_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/1935
> [patch] add declaration number

- lib/ops/web/views/declaration_view.ex
- test/unit/web/controllers/declaration_controller_test.exs
Add declaration_number to response
> [Patch] Add declaration_number to response

- bin/ci/push.sh
- lib/ops/medication_dispense/medication_dispense.ex
- lib/ops/medication_dispense/medication_dispenses.ex
- priv/repo/migrations/20180410134743_add_dispensed_by_to_medication_dispenses.exs
- test/support/factory.ex
- test/unit/web/controllers/medication_dispense_controller_test.exs
Add dispensed_by field to medication dispenses
> Add dispensed_by field to medication dispenses

- .gitignore
- lib/ops/contract/contract.ex
- lib/ops/contract/contract_search.ex
- lib/ops/contract/contracts.ex
- lib/ops/web/controllers/contract_controller.ex
- lib/ops/web/router.ex
- lib/ops/web/views/contract_view.ex
- priv/repo/migrations/20180417091537_create_contract.exs
- test/support/factory.ex
- test/unit/web/controllers/contract_controller_test.exs
- test/unit/web/controllers/medication_request_controller_test.exs
https://github.com/edenlabllc/ehealth.api/issues/2243
> [minor] get contract list #2243

- apps/core/lib/core/rpc/rpc.ex
- apps/core/test/unit/rpc_test.exs
> Add search_declarations on rpc

- apps/core/lib/core/rpc/rpc.ex
- apps/core/test/unit/rpc_test.exs
> Generalize get_declaration via rpc

- apps/core/lib/core/rpc/rpc.ex
- apps/core/test/unit/rpc_test.exs
> Add temporary filter to search declarations
